# Generated by Django 6.0 on 2025-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.CharField(blank=True, choices=[('NAI_MOM', 'Nairobi – Mombasa'), ('NAI_KIS', 'Nairobi – Kisumu'), ('NAI_MAL', 'Nairobi – Malindi'), ('MOM_NAI', 'Mombasa – Nairobi'), ('KIS_NAI', 'Kisumu – Nairobi'), ('MAL_NAI', 'Malindi – Nairobi')], max_length=20, null=True),
        ),
    ]
