# Generated by Django 6.0 on 2025-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_booking_price_booking_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='luggage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
