# Generated by Django 6.0 on 2025-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_booking_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mpesa_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mpesa_callback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
