# Generated by Django 6.0 on 2025-12-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_booking_mpesa_amount_booking_mpesa_callback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_callback',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_checkout_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mpesa_receipt',
        ),
    ]
